version: '3.8'

services:
  dbmysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # зададим пароль пользователя root чтобы, можно было подключаться к mysql mysqld-exporterом

  nginxproxy:
    image: nginx:latest
    restart: always
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  node-exporter:
    image: prom/node-exporter:latest
    network_mode: "host" 
#    ports:
#      - 9100:9100

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    ports:
      - 9104:9104
    command:
      - "--collect.global_status"
      - "--collect.info_schema.innodb_metrics"
      - "--collect.info_schema.processlist"
    volumes:
      - ./.my.cnf:/.my.cnf:ro
    depends_on:
      - dbmysql # включим зависимость запуска mysqld-exporter от работы контейнера dbmysql

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host" 
#    ports:
#      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
#    ports:
#      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS} # зададим пароль пользователя admin, чтобы сразу можно было зайти в админку
      GF_SERVER_ROOT_URL: http://localhost/metrics/
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro # в файле datasources сразу укажем путь к prometheus, чтобы datasource подключился автоматически
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro # в папке dashboards конфиг и дашборды OS General и MySQL, которые добавляются автоматически
    depends_on:
      - prometheus

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        pages_external_url "http://pages.test.com/" 
# активируем gitlab pages путем присвоения страницам адреса, адрес указала рандомный
    ports:
      - 8585:80
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab   
  
  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 9999:8080
